### ISSUE TITLE
Swell

### ISSUE THREAD

**Issue by edpichler** [schachmat/wego#10]
Any possibility off adding swell forecast?

**Comment by schachmat** [comment]
Not in mainline, since it is only useful for coast locations, but you can fork wego and add the feature yourself. The currently used [API](http://www.worldweatheronline.com/api/marine-weather-api.aspx) supports it, so it should not be too hard. When you're done, let me know, and I will link to your repository in the README for all the surfing users.

**Comment by edpichler** [comment]
@schachmat thank you.
