### ISSUE TITLE
Incorrect table alignment under some terminal emulators due to double-width characters

### ISSUE THREAD

**Issue by ronjouch** [schachmat/wego#111]
This is a followup to discussion on [Alacritty commit 3ad68699](https://github.com/jwilm/alacritty/commit/3ad6869967899324cbd7d052187857f1530cdf39#commitcomment-21122228) ([Alacritty](https://github.com/jwilm/alacritty) is a *"cross-platform, GPU-accelerated terminal emulator"*).

The problem is that, in some terminals, wego 2.0 table alignment suffers from the width of the unicode characters used (cloud, sun, etc). See for yourself:

* GNOME Terminal:  
![selection_002](https://cloud.githubusercontent.com/assets/522085/23511136/323c4116-ff2a-11e6-880b-1c4297b3b352.png)
* Alacritty:  
![selection_001](https://cloud.githubusercontent.com/assets/522085/23511156/3d168bd2-ff2a-11e6-83b7-5c27722867f2.png)

To me that looked like a bug in Alacritty, but its main developer, @jwilm, [comments](https://github.com/jwilm/alacritty/commit/3ad6869967899324cbd7d052187857f1530cdf39#commitcomment-21125497) that:

> I believe this is a bug with `wego`. They don't account that terminals may display a cloud as 1 or 2 columns. GNOME Terminal appears to think the cloud icons are only single width. Alacritty (correctly) handles them as double width. We are using the Unicode 9 definitions for wide chars, so that may account for the difference.
> 
> In the `wego` emoji frontend,
> 
>    ```go
>    ret = append(ret, fmt.Sprintf("%v %v %v", cur[1], icon[0], c.formatTemp(cond)))
>    ```
> 
> you can see that there's a space after the icon in the `Sprintf` format string. It's not visible in GNOME Terminal because it's under the emoji. You can see it in Alacritty because we account for the double width characters.
> 
> `wego` should be using the goto functionality of terminals to handle both cases.

**Comment by schachmat** [comment]
Heyho @ronjouch and @jwilm,

Both Icons you are using in your screenshot ([U+26c5](http://unicode.org/cldr/utility/character.jsp?a=26c5), [U+26c8](http://unicode.org/cldr/utility/character.jsp?a=26c8)) are so called "east asian ambiguous" codepoints. These must be rendered differently depending on your locale. I just added a check to the emoji frontend and tested it works for two differently used locales and in two terminal emulators.

**Comment by ronjouch** [comment]
@schachmat thanks for the fast response. That doesn't look fixed to me, though; see screenshot below. Am I missing something?

![wego-alacritty-not-fixed_2](https://cloud.githubusercontent.com/assets/522085/23618227/b356c75e-025d-11e7-9d02-2c342dcf883d.png)

**Comment by schachmat** [comment]
Heyho @ronjouch,

The issue seems to be that [alacritty does not support east asian ambiguous characters yet](https://github.com/jwilm/alacritty/issues/265). In your screenshot the icons seem to occupy 2 cells, so I assume alacritty currently always renders as in an east-asian locale. The following dirty workaround might provide a correct rendering until the alacritty issue is resolved:
* Install an east-asian locale like `ja_JP.UTF-8`.
* Always run `wego` like this: `LC_CTYPE="ja_JP.UTF-8" wego [PARAMETERS]`.

If you installed the locale as above you can test with `xterm -cjk_width` and the `LC_CTYPE` setting against `xterm` without the `LC_CTYPE`. It should provide a two cell wide "partly cloudy" icon in the first and a one cell wide icon in the second case.

**Comment by jwilm** [comment]
@schachmat only one of the glyphs you linked to is ambiguous width. These classifications changed in Unicode 9.0, and it might be that wego and Alacritty are using different definitions.

> I assume alacritty currently always renders as in an east-asian locale.

Quite the opposite, actually. We don't correctly handle ambiguous width characters for those locales, but they should be fine for everyone else.

**Comment by ronjouch** [comment]
I'm a bit lost among this terminalese, but in case that helps/confirms what you are discussing, @schachmat @jwilm, the `LC_CTYPE` trick improves things, but only *partially* works around the issue:

![wego-lc_ctype](https://cloud.githubusercontent.com/assets/522085/23631392/518b4a02-028c-11e7-9070-ac712b29e0cf.png)

**Comment by schachmat** [comment]
Heyho @jwilm, @ronjouch,

Thanks for the update. `wego` is using `go-runewidth` from @mattn to compute rune widths. This package [seems to use unicode 9.0](https://github.com/mattn/go-runewidth/commit/afa37cd08cb2a2cdecf274db34958a20a1f00607) for a while now, so if alacritty is also using unicode 9.0 the definitions should be the same, right?

The issue in the workaround screenshot is probably related to the dash between the min and max temperatures. Maybe the width property of that rune changed as well or the original author of the frontend did not notice the issue in the first place. I'll investigate.

**Comment by mattn** [comment]
Unfortunately, go-runewidth had switch to Unicode 9.0 . I'm sorry if you get wrong.
As you mentioned at here, some character's widths are changed at the commit. If you want to specify CJK width forcibly, please set `runewidth.DefaultCondition.EastAsian = true`.

**Comment by schachmat** [comment]
Heyho @mattn, @jwilm,

I am totally for using the latest unicode standard! My problem is that still I don't quite understand where the issue comes from exactly.

To provide a correct table layout, `wego` needs to know how wide each rune is going to be rendered. Therefore I use `go-runewidth` which should give the correct width according to the unicode 9.0 standard. Now for the whole system to work there are two requirements. First, the terminal emulator obviously has to use the same standard, which is why I prefer the latest one available ("support latest standard" is a better feature-request than "please don't support the latest standard" :wink:). Second, `go-runewidth` and the terminal emulator must agree on the ambiguous wide runes (do we use double width or single width?). To my knowledge of terminal emulators this can only be achieved portably with locales - there does not seem to be a way for applications to force the terminal emulator to use a specific setting. Therefore setting `runewidth.DefaultCondition.EastAsian = true` will not work as it only fixes the setting for one of both components.

Now the issue could be located in either of our three projects. I'll check my code again and also try to verify that `go-runewidth` returns the width I am expecting for each rune. Since I don't have a rust environment installed I can't check alacritty currently.

**Comment by jwilm** [comment]
Thanks for the detailed follow up @schachmat. 

> My problem is that still I don't quite understand where the issue comes from exactly.

That makes (at least) two of us!

I've spent some more time investigating on my side this morning, and there's a chance this is due to Alacritty not handling the variation selector on some of those glyphs (perhaps rendering them as an extra space). I don't know conclusively yet, but I'll follow up as time permits.

**Comment by jwilm** [comment]
I just noticed that rendering appears to be broken in gnome-terminal in the latest version.

![image](https://cloud.githubusercontent.com/assets/4285147/23669271/664dd702-0318-11e7-8c56-7aa72b4ecf6a.png)

The same version in Alacritty has the opposite spacing problem:

![image](https://cloud.githubusercontent.com/assets/4285147/23669321/91ce5938-0318-11e7-86e1-10d9c8012ebb.png)

Thinking about it a bit more, command-line applications are always going to have the problem that some terminals use older Unicode definitions, and others newer. The only way to handle both properly is to avoid reliance on the terminal spacing for wide characters. This could be done via _goto column_ commands. The escape sequence is `\x1b[%dG` to go to a *specific* column. The emoji renderer should probably use that for maximum portability. For a well-known example, `vim` does something very similar when encountering wide characters.

Naturally there's still an issue with Alacritty and the variation selector handling.

**Comment by jwilm** [comment]
After fixing the variation selector bug in Alacritty, the current version of `wego` renders correctly:

![image](https://cloud.githubusercontent.com/assets/4285147/23671437/167b98ec-0320-11e7-9d14-1179809b90f3.png)

**Comment by schachmat** [comment]
Heyho @jwilm,

Thanks for your thoughts on the issue and the quick fix of the variation selector code!

To be honest I don't even know, why the author of this frontend used a variation selector for the `PartlyCloudy` icon in the first place.

I'll think about using the goto column escape code, but intuitively I don't think it's the best solution:
* It provides maintainers with an argument for laziness (well, we don't have to adapt the new unicode standard yet…).
* There might be overdraw after the border at the end of line. Assume a japanese description text rendered longer than the cells right-border.

I'll leave this issue open until I have a final decision. Thank you all for participating!

**Comment by ronjouch** [comment]
> *After fixing the variation selector bug in Alacritty, the current version of wego renders correctly*

@jwilm just to be sure: I don't see it fixed here (fresh Alacritty + wego HEAD builds), I guess your fix is still in an unmerged branch?

**Comment by jwilm** [comment]
@ronjouch Yeah, still on my machine. I'll push up a branch, but it's not ready to merge into master. Let's continue this discussion on the Alacritty tracker or IRC.

**Comment by schachmat** [comment]
So I assume there is nothing left to do here and will close the issue now. If you find further issues feel free to reopen or create a new issue.
