### ISSUE TITLE
Move config file to $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by Bisaloo** [schachmat/wego#116]
The standard location for config files is not `$HOME` but `$XDG_CONFIG_HOME`, which default to `$HOME/.config/`.

More info:

- https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
- https://wiki.archlinux.org/index.php/XDG_Base_Directory_support

You will find plenty of projects have moved their config files to `$XDG_CONFIG_HOME` to comply with this standard. I think `wego` should do the same and move the config to something like `$XDG_CONFIG_HOME/wego/wegorc`.

Beyond standard compliance, this helps a lot users who want to sync config files between several computers. Instead of having files scattered all over `$HOME`, they are all tidy and neat in one place.

**Comment by schachmat** [comment]
Heyho @Bisaloo,

As far as I know and my quick search turned out there is no support for the `$XDG_CONFIG_HOME` env var in Windows. If you can provide a patch which shifts the config to `$XDG_CONFIG_HOME` if available in a portable way and is not more complex than the existing code, I'll consider applying it.

**Comment by schachmat** [comment]
Oh and this is the place you want to be looking at for the code: https://github.com/schachmat/ingo/blob/master/in.go#L59

**Comment by Bisaloo** [comment]
No, you're right. It doesn't exist in Windows as far as I know.

I think some softwares manage to handle that in a portable way. I will try to look into it and submit a PR if I find something interesting.

**Comment by Bisaloo** [comment]
@schachmat, would you be okay with moving the config file to `$HOME/.config/wego/wegorc` for non-XDG-compliant platforms?

**Comment by schachmat** [comment]
Maybe. Depends on the patch. I can't come up quickly with a way to achieve this equally simple as the existing approach. Basically `user.Current().HomeDir` is used for portability and ensured to be correct since it is in the Go core library.

Doing the platform switch manually would always be an additional maintenance effort for new platforms. A better solution would be to move the issue upstream and try to merge a new field like `user.Current().ConfigDir` to the `struct User`, which would then use `XDG_CONFIG_HOME` on linux platforms, `APP_DATA` on Windows, etc.

**Comment by Bisaloo** [comment]
I see what you mean and I agree: this addition would inevitably add some level of complexity.

It's an interesting idea to take it upstream. I don't know anything about the Go community. Do you think it has any chance of being considered? It is apparently an increasing demand in Go projects ([source](https://github.com/search?l=Go&q=xdg&type=Issues&utf8=%E2%9C%93)).

Another solution would be to use [one of those libraries](https://github.com/search?l=Go&o=desc&q=xdg&s=updated&type=Repositories&utf8=%E2%9C%93), which basically achieve the behaviour you are describing. It would add another dependency though.

**Comment by schachmat** [comment]
I think the sources you listed show that there is enough demand for this addition to be considered upstream. I also could not find a PR to add anything related to `XDG_CONFIG_HOME` to the golang project in the past, so it is well worth a try. Let me know if you're planning to do this, otherwise I might add it to my own todo-list. ;)

On the topic of adding another lib dependency: I don't have a problem with applications depending on multiple libraries, but I don't like the idea of a library itself depending on other libraries. Sometimes it's necessary, but if we can avoid it, it helps to keep the dependency tree low.

**Comment by Bisaloo** [comment]
I was thinking of filing an issue since I don't know anything about the Go language but if you think you may be able to submit a PR at some point, please by all means, go ahead!

Thank you for your time! I will try to keep a close look at this issue.
