### ISSUE TITLE
Yahoo Weather support

### ISSUE THREAD

**Issue by miguelmota** [schachmat/wego#121]
Do you have plans for supporting Yahoo Weather API?

https://developer.yahoo.com/weather/

**Comment by Bean6754** [comment]
I personally wouldn't use the Yahoo Weather API, but that's because of a different issue that I have with the Yahoo and Oath Inc. (now a subsidiary of Verizon Media) data collection and email snooping.

**"Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. "**

There is the new Yahoo [https://weather-ydn-yql.media.yahoo.com/forecastrss], this is the only documentation I could find on it: [https://developer.yahoo.com/weather/documentation.html]

**Comment by miguelmota** [comment]
Thanks for the info. Closing issue
