### ISSUE TITLE
Some changes made to the config are being overwritten

### ISSUE THREAD

**Issue by benoitj** [schachmat/wego#125]
Changes made to the configuration other than the expected attribute names are being overwritten. 

Alteration to the ordering, removing unused configuration attributes, or added comments are being removed by wego after each execution. 

A side effect of this behavior is if you add a typo on a valid configuration attribute name, it would remove it. For example, I removed one char from my forecast-api.key, ran wego and the key got replaced by a blank one + the attribute with the type is moved at the bottom with a "deprecated" notice.

Not sure what is the intent with overwritting the configuration after each run, but it is definitively unexpected.

**Comment by schachmat** [comment]
This was an intentional design choice for https://github.com/schachmat/ingo. It helps keep the code simple (KISS principle). I don't see any critical issues in your message, but if you feel that a particular critical user journey with ingo is problematic and warrants an actual bug, please open one with the ingo project.
