### ISSUE TITLE
new frontend without ASCII art icon output, for tiny terminals?

### ISSUE THREAD

**Issue by krompus** [schachmat/wego#53]
I'm very pleased with your program! I would like to request the feature above, as I sometimes want to launch the program in a small terminal like [this screenshot comparing the output on a narrow terminal and a wider terminal.](http://i.imgur.com/K3KinkB.png)

I lack the expertise to do it myself. Heck, I only just learned how to `git clone`, lol. :)

The standard output is 125 characters wide when including the table. The art takes up about 60 characters of that width. If one were to remove just the table lines, one could gain another five characters, putting the potential width with these changes approximately a mere sixty characters wide (text only).

Do you think it would be possible to implement an argument that removes the art and/or the table? (the image at the top for the present time's weather can stay, as it does not affect the total width).

Also note that I tend to bundle this with the `date` command in my `.bashrc`, like so: `alias weather="date && wego"` to receive this output:

```
$ weather 1
Tue Aug  4 00:19:51 EDT 2015
Weather for City:...(etc)
```

I'll poke around in the code to see if I can figure out how to do it myself.

​Cheers!​
## 

:(){ :|:& };:​​

**Comment by schachmat** [comment]
Heyho @krompus,

Your feature request should ultimately be solved by #1, but here are some hints for you to get going:

* The Icons are included [here](https://github.com/schachmat/wego/blob/master/we.go#L437). If you want the icon for the current condition to persist, you would have to split on the bool value of current.
* After removing the icons, the table should still have fixed column widths, you have to adapth the header (here)[https://github.com/schachmat/wego/blob/master/we.go#L474] and if you want to remove the column separators (here)[https://github.com/schachmat/wego/blob/master/we.go#L467] as well.
* Implementing that as a commandline flag is hard, since wego uses custom flag parsing. You could either hardcode your changes (then the normal table output will not work anymore), or add a config switch (grep for `config`, harder to implement).

I'll leave this issue open for a while to collect relevant discussion.
